version: '3.7'
services:
    retroarch-web:
        image: retroarch
        build:
            context: .
            dockerfile: Dockerfile
        container_name: retroarch
        volumes:
            - /srv/docker-data/retroarch:/var/www/html/assets/cores/retroarch
        ports:
            - '8182:80'
        restart: unless-stopped
